export {default as HeroSection} from "./HeroSection"
export {default as AboutSection} from "./AboutSection"
export {default as ProjectSection} from "./ProjectSection"
export {default as SkillSection} from "./SkillSection"
export {default as TimelineSection} from "./TimelineSection"
export {default as ContactSection} from "./ContactSection"